name: default
channels:
- conda-forge
- conda-forge/label/fenics-dev
- nodefaults
dependencies:
- svmtk >=1.3.0
- fenics >=2019.1.0
- h5py >=3.12.1,<4
- python >=3.9
- pip
- pip:
  - -e .
  - loguru
  - sympy
  - matplotlib
  - meshio[all]*
  - numpy
  - gmsh
  - h5py>=3.12.1

