name: pantarei
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7, <3.12
  - pip
  - h5py
  - fenics
  - numpy
  - matplotlib
  - jupyter
  - meshio
  - svmtk <= 1.3.0
  - pip:
    - git+https://github.com/MiroK/ulfy.git

