[tool.poetry]
name = "pantarei"
version = "0.1.0"
description = ""
authors = ["jorgenriseth <jnriseth@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fenics = "^2019.1.0"
matplotlib = "^3.5.1"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
