name: PyPI publish

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
              3.9
              3.10
              3.11
              3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
